-- Create the reports table
create table public.reports (
  id bigint generated by default as identity primary key,
  filename text not null unique,
  title text,
  report_date text,
  quarter text,
  year integer,
  status text default 'pending'::text,
  extracted_at timestamptz,
  created_at timestamptz default now()
);

-- Regions
create table public.regions (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- Building types
create table public.building_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text
);

-- Size bands
create table public.size_bands (
  id bigint generated by default as identity primary key,
  label text not null unique,
  min_sqft double precision,
  max_sqft double precision
);

-- Price indices (the main data table)
create table public.price_indices (
  id bigint generated by default as identity primary key,
  report_id bigint references public.reports not null,
  region_id bigint references public.regions,
  building_type_id bigint references public.building_types,
  size_band_id bigint references public.size_bands,
  index_value double precision,
  base_period text,
  price_per_sqft double precision,
  currency text default 'GBP'::text,
  notes text,
  unique (report_id, region_id, building_type_id, size_band_id)
);

-- Indexes for performance
create index idx_price_indices_report on public.price_indices(report_id);
create index idx_price_indices_region on public.price_indices(region_id);
create index idx_price_indices_building_type on public.price_indices(building_type_id);
create index idx_price_indices_size_band on public.price_indices(size_band_id);
create index idx_reports_year on public.reports(year);
create index idx_reports_quarter on public.reports(quarter);

-- Storage bucket for PDF uploads
insert into storage.buckets (id, name, public) values ('reports', 'reports', true);
