-- 003: tender price inflation (TPI) forecasts, as published in consultants'
-- quarterly reports (starting with Gardiner & Theobald).

alter table public.reports
  add column publisher text,
  -- 1–4, for ordering reports within a year (seasonal editions are mapped to a quarter).
  add column period_quarter smallint check (period_quarter between 1 and 4);

-- One report per publisher per period, whatever the uploaded file was called.
create unique index reports_publisher_period_key
  on public.reports (publisher, year, period_quarter)
  where publisher is not null;

create table public.tpi_forecasts (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports (id) on delete cascade,
  region text not null,
  -- Calendar year the forecast is for (annual Jan–Dec tender price change).
  forecast_year integer not null,
  -- This report's forecast, % change.
  change_pct numeric(5, 2),
  -- The same publisher's previous report's forecast for that year, % change.
  previous_change_pct numeric(5, 2),
  unique (report_id, region, forecast_year)
);

create index tpi_forecasts_region_year on public.tpi_forecasts (region, forecast_year);

alter table public.tpi_forecasts enable row level security;
create policy "Public read" on public.tpi_forecasts for select to anon, authenticated using (true);

-- Flat view: each forecast with the report it came from.
create view public.tpi_forecast_rows
with (security_invoker = true) as
select
  f.id,
  f.report_id,
  r.publisher,
  r.quarter as period_label,
  r.year as period_year,
  r.period_quarter,
  f.region,
  f.forecast_year,
  f.change_pct::double precision as change_pct,
  f.previous_change_pct::double precision as previous_change_pct
from public.tpi_forecasts f
join public.reports r on r.id = f.report_id;

grant select on public.tpi_forecast_rows to anon, authenticated;
